In [2]:
import numpy as np

## Create Vector

In [6]:
#create a row vector
row_vector = np.array([10,15,20])
print(row_vector)

#create a col vector
print('nhập toạ độ x')
cor_x = int(input())
print('nhập toạ độ y')
cor_y = int(input())
print('nhập toạ độ z')
cor_z = int(input())
col_vector = np.array([[cor_x],[cor_y],[cor_z]])
print(col_vector)

[10 15 20]
nhập toạ độ x
10
nhập toạ độ y
15
nhập toạ độ z
20
[[10]
 [15]
 [20]]


## Create Matrix

In [53]:
#tạo ma trận 
matrix = np.array([[10,20,30], [40,50,60]])
print(matrix)

#tạo ma trận 0
matrix_zero = np.zeros([4,4])
print(matrix_zero)

#tạo ma trận 1
matrix_one = np.ones([3,3])
print(matrix_one)

#tạo ngẫu nhiên 4 số từ 0 đến 10 (ma trận hàng)
matrix_random_value = np.random.randint(0,10,4)
print(matrix_random_value)

#3 số từ mean(1.0) và std(2.0)
print(np.random.normal(1.0,2.0,3))

[[10 20 30]
 [40 50 60]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[6 0 1 6]
[ 1.44954734 -0.47013859  0.60596227]


In [22]:
#number of col and row of matrix
print(matrix.shape)

#number of elements (m*n)
print(matrix.size)

#number of dimensions 
print(matrix.ndim)

(3, 3)
9
2


## Accessing Element

In [19]:
row_vector = np.array([10,20,30,40,50,60])
matrix = np.array ([[10,20,30],[40,50,60],[70,80,90]])
print('*row vector: \n',row_vector)
print('*matrix: \n',matrix)

print('*2nd element of vector:', row_vector[1])
print('*3rd row 3rd column:', matrix[2,2])
print('*All element of vector:', row_vector[:])
print('*Last element of vector:', row_vector[-1])
print('*First 2 rows and all the columns:\n', matrix[:2,:])

*row vector: 
 [10 20 30 40 50 60]
*matrix: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
*2nd element of vector: 20
*3rd row 3rd column: 90
*All element of vector: [10 20 30 40 50 60]
*Last element of vector: 60
*First 2 rows and all the columns:
 [[10 20 30]
 [40 50 60]]


## Min and Max

In [27]:
print('The max element is', np.max(matrix))
print('The min element is', np.min(matrix))
print('The max element in each column', np.max(matrix, axis=0))
print('The max element in each row', np.max(matrix, axis=1))
print('The average of matrix is', np.mean(matrix))

The max element is 90
The min element is 10
The max element in each column [70 80 90]
The max element in each row [30 60 90]
The average of matrix is 50.0


## Reshape

In [33]:
print(matrix.reshape(9,1))
print(matrix.reshape(1,-1))
print(matrix.reshape(9))
print('convert to 1-d array\n',matrix.flatten())

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
[[10 20 30 40 50 60 70 80 90]]
[10 20 30 40 50 60 70 80 90]
convert to 1-d array
 [10 20 30 40 50 60 70 80 90]


## Transpose

In [34]:
print(matrix.T)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


## Diagonal Lấy đường chéo chính

In [35]:
print(matrix.diagonal())

[10 50 90]


## Adding, Subtracting and Multiplying Matrices

In [45]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]]) 
print('cộng 2 ma trận:\n',np.add(matrix_1, matrix_2))
print('trừ 2 ma trận:\n',np.subtract(matrix_1, matrix_2))
print('nhân 2 ma trận:\n',matrix_1.dot(matrix_2))
print('x3 ma trận đầu:\n',matrix_1*3)
print('chia 2 ma trận:\n',np.matmul(matrix_1, matrix_2))

cộng 2 ma trận:
 [[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
trừ 2 ma trận:
 [[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
nhân 2 ma trận:
 [[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]
x3 ma trận đầu:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
chia 2 ma trận:
 [[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]
